# Generated by Django 5.0 on 2024-01-22 05:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coupon', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coupon',
            old_name='discount_percentage',
            new_name='discount_price',
        ),
    ]
