# Generated by Django 5.0 on 2024-01-30 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupon', '0006_alter_coupon_valid_from_alter_coupon_valid_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='maximum_discount',
            field=models.DecimalField(decimal_places=2, default=2000, max_digits=10),
        ),
        migrations.AddField(
            model_name='coupon',
            name='maximum_usage_count',
            field=models.PositiveIntegerField(default=5),
        ),
        migrations.AddField(
            model_name='coupon',
            name='minimum_cart_value',
            field=models.DecimalField(decimal_places=2, default=300, max_digits=10),
        ),
    ]
