# Generated by Django 5.0 on 2024-01-30 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupon', '0007_coupon_maximum_discount_coupon_maximum_usage_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='maximum_discount',
            field=models.DecimalField(decimal_places=2, default=2000, max_digits=10, null=True),
        ),
    ]
