# Generated by Django 5.0.1 on 2024-02-06 04:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpage', '0016_product_offer'),
        ('offer', '0002_offer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='offers_for_product', to='adminpage.product'),
        ),
    ]
