# Generated by Django 5.0.1 on 2024-02-06 05:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0003_alter_offer_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offer',
            name='discount_amount',
        ),
    ]
