# Generated by Django 5.0.1 on 2024-02-06 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0005_remove_categoryoffer_discount_percentage_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productoffer',
            name='product',
        ),
        migrations.DeleteModel(
            name='CategoryOffer',
        ),
        migrations.DeleteModel(
            name='ProductOffer',
        ),
    ]
