# Generated by Django 5.0 on 2023-12-28 04:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminpage', '0002_userprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='user',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
