# Generated by Django 5.0 on 2024-01-25 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpage', '0013_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_type',
            field=models.CharField(choices=[('COD', 'Cash on Delivery'), ('WALLET', 'Wallet'), ('Paypal', 'Paypal')], max_length=10),
        ),
    ]
