# Generated by Django 5.0.1 on 2024-02-06 04:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpage', '0015_brand_product_brand'),
        ('offer', '0002_offer'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='offer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products_with_offer', to='offer.offer'),
        ),
    ]
