# Generated by Django 5.0.1 on 2024-02-06 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminpage', '0016_product_offer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='offer',
        ),
    ]
