# Generated by Django 5.0.1 on 2024-02-06 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpage', '0017_remove_product_offer'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariant',
            name='price_adjusted',
            field=models.BooleanField(default=False),
        ),
    ]
