# Generated by Django 5.0 on 2024-01-01 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0003_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
