# Generated by Django 5.0.1 on 2024-02-01 15:55

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdetails',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
